import { AsyncLocalStorage } from 'node:async_hooks';
import path from 'node:path';
import fs from 'node:fs';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Row = any;

/**
 * Postgres storage for the Umami Studio operations dashboard.
 * - Production: DATABASE_URL (e.g. Neon) through node-postgres.
 * - Local development and tests: an embedded Postgres (PGlite) in OPS_DATA_DIR, or in memory.
 * Workspace records keep the dashboard's own JSON shape; accounts, sessions and tokens are relational and secrets
 * are stored only as hashes. Transactions and activity are append-only (triggers); only demo rows can be removed.
 */
const SCHEMA = `
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  has_email INTEGER NOT NULL DEFAULT 1,
  notify_email TEXT,
  role TEXT NOT NULL CHECK (role IN ('admin','staff')),
  status TEXT NOT NULL CHECK (status IN ('invited','active','disabled')),
  password_hash TEXT,
  must_change_password INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  created_by INTEGER REFERENCES users(id),
  last_login_at TEXT,
  disabled_at TEXT
);
CREATE TABLE IF NOT EXISTS auth_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  token_hash TEXT NOT NULL UNIQUE,
  purpose TEXT NOT NULL CHECK (purpose IN ('invite','reset')),
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL,
  created_by INTEGER REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS auth_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id),
  actor_id INTEGER REFERENCES users(id),
  event TEXT NOT NULL,
  detail TEXT
);
CREATE TABLE IF NOT EXISTS login_failures (
  key TEXT PRIMARY KEY,
  count INTEGER NOT NULL,
  until TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  updated_by TEXT
);
CREATE TABLE IF NOT EXISTS inventory (
  name TEXT PRIMARY KEY,
  data TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS transactions (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id TEXT NOT NULL UNIQUE,
  data TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id),
  demo INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS activity (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time TEXT NOT NULL,
  actor TEXT NOT NULL,
  entity TEXT NOT NULL,
  text TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id),
  demo INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS activity_time ON activity(time);
CREATE TABLE IF NOT EXISTS kv (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS uploads (
  name TEXT PRIMARY KEY,
  content_type TEXT NOT NULL,
  data BYTEA NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS email_outbox (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TEXT NOT NULL,
  to_addr TEXT NOT NULL,
  subject TEXT NOT NULL,
  body TEXT NOT NULL,
  status TEXT NOT NULL,
  error TEXT
);

CREATE OR REPLACE FUNCTION ops_append_only() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'UPDATE' OR OLD.demo = 0 THEN
    RAISE EXCEPTION '% are append-only', TG_TABLE_NAME;
  END IF;
  RETURN OLD;
END $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION ops_no_user_delete() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'users are never deleted; disable them instead';
END $$ LANGUAGE plpgsql;
CREATE OR REPLACE TRIGGER transactions_append_only BEFORE UPDATE OR DELETE ON transactions FOR EACH ROW EXECUTE FUNCTION ops_append_only();
CREATE OR REPLACE TRIGGER activity_append_only BEFORE UPDATE OR DELETE ON activity FOR EACH ROW EXECUTE FUNCTION ops_append_only();
CREATE OR REPLACE TRIGGER users_no_delete BEFORE DELETE ON users FOR EACH ROW EXECUTE FUNCTION ops_no_user_delete();
`;

export const DATA_DIR = process.env.OPS_DATA_DIR ?? path.resolve('data', 'ops');

interface Queryable { query(sql: string, params?: unknown[]): Promise<{ rows: Row[]; affectedRows?: number; rowCount?: number | null }> }
interface Driver extends Queryable {
  exec(sql: string): Promise<unknown>;
  transaction<T>(fn: (q: Queryable) => Promise<T>): Promise<T>;
  close(): Promise<void>;
}

async function pgDriver(url: string): Promise<Driver> {
  const { default: pg } = await import('pg');
  const local = /@(localhost|127\.0\.0\.1)[:/]/.test(url);
  const pool = new pg.Pool({ connectionString: url, max: Number(process.env.PG_POOL_MAX || 3), ssl: local ? undefined : { rejectUnauthorized: true } });
  return {
    query: (sql, params) => pool.query(sql, params as unknown[]),
    exec: sql => pool.query(sql),
    async transaction(fn) {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        const out = await fn({ query: (sql, params) => client.query(sql, params as unknown[]) });
        await client.query('COMMIT');
        return out;
      } catch (e) {
        await client.query('ROLLBACK').catch(() => {});
        throw e;
      } finally {
        client.release();
      }
    },
    close: () => pool.end(),
  };
}

async function pgliteDriver(where: string): Promise<Driver> {
  const { PGlite } = await import('@electric-sql/pglite');
  if (where !== 'memory://') fs.mkdirSync(where, { recursive: true });
  const db = await PGlite.create(where);
  return {
    query: (sql, params) => db.query(sql, params as unknown[]),
    exec: sql => db.exec(sql),
    transaction: fn => db.transaction(tx => fn({ query: (sql, params) => tx.query(sql, params as unknown[]) })),
    close: () => db.close(),
  };
}

let driver: Promise<Driver> | null = null;
const txScope = new AsyncLocalStorage<Queryable>();

/** Connects (once per process) and brings the schema up to date. */
export function openDb(target = process.env.DATABASE_URL || process.env.POSTGRES_URL || process.env.OPS_PG_DIR || path.join(DATA_DIR, 'pg')): Promise<Driver> {
  if (!driver) {
    driver = (async () => {
      const d = /^postgres(ql)?:\/\//.test(target) ? await pgDriver(target) : await pgliteDriver(target);
      // The lock keeps two cold starts from migrating at the same moment.
      await d.exec(`SELECT pg_advisory_lock(727001);\n${SCHEMA}\nSELECT pg_advisory_unlock(727001);`);
      return d;
    })();
    driver.catch(() => { driver = null; });
  }
  return driver;
}

export async function closeDb() {
  if (driver) { const d = await driver; driver = null; await d.close(); }
}

/** SQL is written with ? placeholders; Postgres wants $1, $2, … */
function toPg(sql: string) {
  let i = 0, out = '', quoted = false;
  for (const ch of sql) {
    if (ch === "'") quoted = !quoted;
    out += ch === '?' && !quoted ? `$${++i}` : ch;
  }
  return out;
}

async function q(sql: string, params: unknown[]) {
  const target: Queryable = txScope.getStore() ?? await openDb();
  return target.query(toPg(sql), params.map(p => (p === undefined ? null : p)));
}

export const now = () => new Date().toISOString();
export const get = async (sql: string, ...p: unknown[]): Promise<Row> => (await q(sql, p)).rows[0];
export const all = async (sql: string, ...p: unknown[]): Promise<Row[]> => (await q(sql, p)).rows;
export const run = async (sql: string, ...p: unknown[]) => {
  const r = await q(sql, p);
  return { changes: Number(r.affectedRows ?? r.rowCount ?? 0), rows: r.rows };
};

/** Runs fn in one database transaction; nested calls join the outer one. */
export async function tx<T>(fn: () => Promise<T>): Promise<T> {
  if (txScope.getStore()) return fn();
  const d = await openDb();
  return d.transaction(client => txScope.run(client, fn));
}

export async function kvGet<T>(key: string, fallback: T): Promise<T> {
  const r = await get('SELECT value FROM kv WHERE key=?', key);
  return r ? (JSON.parse(r.value) as T) : fallback;
}
export async function kvSet(key: string, value: unknown) {
  await run('INSERT INTO kv (key, value) VALUES (?, ?) ON CONFLICT (key) DO UPDATE SET value=excluded.value', key, JSON.stringify(value));
}

/** Monotonic counter bumped on every workspace write, so open dashboards know to refresh. */
export async function bumpRevision(): Promise<number> {
  const r = await get(`INSERT INTO kv (key, value) VALUES ('revision', '1')
    ON CONFLICT (key) DO UPDATE SET value = ((kv.value)::int + 1)::text RETURNING value`);
  return Number(r.value);
}
